trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# ==========================================
# 1. RESTAURAR DEPENDÊNCIAS (.NET 8)
# ==========================================
- task: DotNetCoreCLI@2
  displayName: 'Restaurar Pacotes Nuget'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# ==========================================
# 2. PUBLICAR A API (Api10-EF-Jwt)
# ==========================================
- task: DotNetCoreCLI@2
  displayName: 'Publicar - API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Api10-EF-Jwt/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)/API'
    zipAfterPublish: true

# ==========================================
# 3. PUBLICAR O FRONT-END (Razor-Consumir-Api-Jwt)
# ==========================================
- task: DotNetCoreCLI@2
  displayName: 'Publicar - FrontEnd'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Razor-Consumir-Api-Jwt/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)/FrontEnd'
    zipAfterPublish: true

# ==========================================
# 4. DISPONIBILIZAR OS ARQUIVOS (Artefatos)
# ==========================================
- task: PublishBuildArtifacts@1
  displayName: 'Publicar Artefatos Finais'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
