// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaERPOnlineForcaDeVendasAPI.InfraEstrutura.Data;

#nullable disable

namespace InfraEstrutura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529174731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SistemaERPOnlineForcaDeVendasAPI.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LucroMaximo")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("LucroMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("PrecoSugerido")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("PrecoVendaMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("ValorUltimaCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaERPOnlineForcaDeVendasAPI.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("TaxaPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
